name: Flame_initial
description: first flutter flame test
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  showcaseview: ^3.0.0
  flutter_reactive_ble: ^5.3.1
 
  
flutter:
  assets:
    - assets/

